containers:
- name: kafka
  image: confluentinc/cp-kafka:latest
  ports:
    - containerPort: 9092
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
  command:
    - sh
    - -c
    - |
      /etc/confluent/docker/run
  env:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka:9092
    - name: KAFKA_LISTENERS
      value: PLAINTEXT://0.0.0.0:9092
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_LOG_DIRS
      value: "/var/lib/kafka/data"
  volumeMounts:
    - name: kafka-data
      mountPath: /var/lib/kafka/data
